//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_Delivery
    {
        public int Provider_DeliveryID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<int> ProviderID { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
